### ISSUE TITLE
[amdgpu] I'm blue (da ba dee, da ba die) (Image format seems misdetected)

### ISSUE THREAD

**Issue by ctrlcctrlv** [isjerryxiao/kmsvnc#7]
![image](https://github.com/isjerryxiao/kmsvnc/assets/838783/57ba7f56-96a1-4262-948a-e7285c551242)

```
[fred@大.狸.agency ~/.cache/yay/kmsvnc-git/src/kmsvnc]$ sudo gdb ./build/kmsvnc -ex 'run -p 5901  -b 10.2.2.2 -4 -d /dev/dri/card0'
GNU gdb (GDB) 13.2
Copyright (C) 2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./build/kmsvnc...
Starting program: /home/fred/.cache/yay/kmsvnc-git/src/kmsvnc/build/kmsvnc -p 5901  -b 10.2.2.2 -4 -d /dev/dri/card0
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
No keyboard layout set from environment variables, use US layout by default
See https://xkbcommon.org/doc/current/structxkb__rule__names.html
drm driver is amdgpu
Plane 40 CRTC 0 FB 0 Type primary
Plane 46 CRTC 0 FB 0 Type primary
Plane 52 CRTC 0 FB 0 Type primary
Plane 58 CRTC 0 FB 0 Type primary
Plane 64 CRTC 95 FB 154 Type primary
Using plane 64 to locate framebuffers
Template framebuffer is 154: 2944x1080 fourcc:875713112 mod:144115188622392067 flags:2
handles 1 1 1 0
offsets 0 13565952 13639680 0
pitches 11776 3072 3072 0
format XR24, modifier AMD:GFX10_RBPLUS,GFX9_64K_R_X,DCC,DCC_RETILE,DCC_INDEPENDENT_64B,DCC_INDEPENDENT_128B,DCC_MAX_COMPRESSED_BLOCK=64B,DCC_CONSTANT_ENCODE,PIPE_XOR_BITS=4,PACKERS=4
[New Thread 0x7fffeb3ff6c0 (LWP 295875)]
[New Thread 0x7fffeabfe6c0 (LWP 295876)]
[New Thread 0x7fffea3fd6c0 (LWP 295877)]
[New Thread 0x7fffe9bfc6c0 (LWP 295878)]
vaapi vendor Mesa Gallium driver 23.3.0-devel for AMD Radeon RX 6900 XT (navi21, LLVM 16.0.6, DRM 3.54, 6.3.7-1-amd-staging-drm-next-git-gb4d88db12014)
va operation error 0x1 operation failed on line 338
got vaapi image:
image fmt: fourcc 1481787202, BGRX, byte_order VA_LSB_FIRST, bpp 32, depth 24, blue_mask 0xff, green_mask 0xff00, red_mask 0xff0000, reserved 0 0 0 0
17/09/2023 19:25:46 Listening for VNC connections on TCP port 5901
[New Thread 0x7fffdbfff6c0 (LWP 295879)]
^C
Thread 1 "kmsvnc" received signal SIGINT, Interrupt.
0x00007ffff7ad5835 in clock_nanosleep () from /usr/lib/libc.so.6
(gdb) list
353	           kmsvnc->disable_input = 1;
354	           break;
355	       case 'n':
356	           kmsvnc->vnc_opt->desktop_name = arg;
357	           break;
358	       case ARGP_KEY_ARG:
359	           return ARGP_ERR_UNKNOWN;
360	       default:
361	           return ARGP_ERR_UNKNOWN;
362	   }
(gdb) p kmsvnc
$1 = (struct kmsvnc_data *) 0x55555557f290
(gdb) p *kmsvnc
$2 = {debug_capture_fb = 0x0, card = 0x7fffffffecd6 "/dev/dri/card0", force_driver = 0x0, vnc_opt = 0x55555557f330, input_wakeup = 0 '\000', disable_input = 0 '\000', va_derive_enabled = -1, debug_enabled = 0 '\000', source_plane = 0, 
  source_crtc = 0, input_width = 0, input_height = 0, input_offx = 0, input_offy = 0, screen_blank = 0 '\000', screen_blank_restore = 0 '\000', drm = 0x5555555b8ca0, input = 0x555555564170, keymap = 0x555555579a50, 
  va = 0x55555559dd10, server = 0x55555575e5a0, shutdown = 0 '\000', capture_cursor = 0 '\000', cursor_bitmap = 0x0, cursor_bitmap_len = 0, buf = 0x5555563c1c30 "", buf1 = 0x555556fe2c40 ""}
(gdb) p *kmsvnc->drm
$3 = {drm_fd = 4, drm_master_fd = 0, drm_ver = 0x555555582350, prime_fd = 5, plane = 0x555555582310, cursor_plane = 0x0, plane_res = 0x555555563e70, mfb = 0x55555558d8b0, cursor_mfb = 0x0, plane_id = 0, mmap_fd = 5, 
  mmap_size = 12718080, mmap_offset = 0, mapped = 0x0, cursor_mapped = 0x0, cursor_mmap_size = 0, skip_map = 1 '\001', funcs = 0x5555555646b0, pixfmt_name = 0x555555564530 "XR24", mod_vendor = 0x555555564bf0 "AMD", 
  mod_name = 0x5555555a93c0 "GFX10_RBPLUS,GFX9_64K_R_X,DCC,DCC_RETILE,DCC_INDEPENDENT_64B,DCC_INDEPENDENT_128B,DCC_MAX_COMPRESSED_BLOCK=64B,DCC_CONSTANT_ENCODE,PIPE_XOR_BITS=4,PACKERS=4", kms_convert_buf = 0x0, 
  kms_convert_buf_len = 0, kms_cpy_tmp_buf = 0x0, kms_cpy_tmp_buf_len = 0, kms_cursor_buf = 0x0, kms_cursor_buf_len = 0, gamma = 0x0}
(gdb) p *kmsvnc->drm_ver
There is no member named drm_ver.
(gdb) p *kmsvnc->drm->drm_ver
$4 = {version_major = 3, version_minor = 54, version_patchlevel = 0, name_len = 6, name = 0x55555559c830 "amdgpu", date_len = 8, date = 0x55555559c810 "20150101", desc_len = 7, desc = 0x55555559cc50 "AMD GPU"}
(gdb)
```

**Comment by isjerryxiao** [comment]
It seems that iHD and mesa is reporting exactly opposite values for blue_mask, green_mask and red_mask. For iHD it is always MSB_FIRST while mesa reports LSB_FIRST. The plan here is to always use the requested format and blindly assume the vaapi driver returns the correct image format.

**Comment by isjerryxiao** [comment]
Also can you please provide the output of `kmsvnc --debug -i`

**Comment by ctrlcctrlv** [comment]
```
[fred@大.狸.agency ~]$ sudo !!
sudo kmsvnc --debug -i
drm driver is amdgpu
Plane 45 CRTC 0 FB 0 Type primary
Plane 50 CRTC 0 FB 0 Type primary
Plane 55 CRTC 0 FB 0 Type primary
Plane 60 CRTC 0 FB 0 Type primary
Plane 65 CRTC 90 FB 153 Type primary
Using plane 65 to locate framebuffers
Template framebuffer is 153: 4864x2160 fourcc:875713112 mod:144115188622392067 flags:2
handles 1 1 1 0
offsets 0 42336256 42541056 0
pitches 19456 5120 5120 0
format XR24, modifier AMD:GFX10_RBPLUS,GFX9_64K_R_X,DCC,DCC_RETILE,DCC_INDEPENDENT_64B,DCC_INDEPENDENT_128B,DCC_MAX_COMPRESSED_BLOCK=64B,DCC_CONSTANT_ENCODE,PIPE_XOR_BITS=4,PACKERS=4
va msg: VA-API version 1.20.0
va msg: Trying to open /usr/lib/dri/radeonsi_drv_video.so
va msg: Found init function __vaDriverInit_1_20
va msg: va_openDriver() returns 0
vaapi vendor Mesa Gallium driver 23.3.0-devel for AMD Radeon RX 6900 XT (navi21, LLVM 16.0.6, DRM 3.52, 6.0.0-1-hdr-git-02753-gff57328e5784)
selected rt_format 131072, alpha 0
image fmt: fourcc 842094158, NV12, byte_order VA_MSB_FIRST, bpp 0, depth 0, blue_mask 0, green_mask 0, red_mask 0, reserved 0 0 0 0
image fmt: fourcc 808530000, P010, byte_order VA_MSB_FIRST, bpp 0, depth 0, blue_mask 0, green_mask 0, red_mask 0, reserved 0 0 0 0
image fmt: fourcc 909193296, P016, byte_order VA_MSB_FIRST, bpp 0, depth 0, blue_mask 0, green_mask 0, red_mask 0, reserved 0 0 0 0
image fmt: fourcc 808596553, I420, byte_order VA_MSB_FIRST, bpp 0, depth 0, blue_mask 0, green_mask 0, red_mask 0, reserved 0 0 0 0
image fmt: fourcc 842094169, YV12, byte_order VA_MSB_FIRST, bpp 0, depth 0, blue_mask 0, green_mask 0, red_mask 0, reserved 0 0 0 0
image fmt: fourcc 1448695129, YUYV, byte_order VA_MSB_FIRST, bpp 0, depth 0, blue_mask 0, green_mask 0, red_mask 0, reserved 0 0 0 0
image fmt: fourcc 844715353, YUY2, byte_order VA_MSB_FIRST, bpp 0, depth 0, blue_mask 0, green_mask 0, red_mask 0, reserved 0 0 0 0
image fmt: fourcc 1498831189, UYVY, byte_order VA_MSB_FIRST, bpp 0, depth 0, blue_mask 0, green_mask 0, red_mask 0, reserved 0 0 0 0
image fmt: fourcc 808466521, Y800, byte_order VA_MSB_FIRST, bpp 0, depth 0, blue_mask 0, green_mask 0, red_mask 0, reserved 0 0 0 0
image fmt: fourcc 1345598516, 444P, byte_order VA_MSB_FIRST, bpp 0, depth 0, blue_mask 0, green_mask 0, red_mask 0, reserved 0 0 0 0
image fmt: fourcc 1346520914, RGBP, byte_order VA_MSB_FIRST, bpp 0, depth 0, blue_mask 0, green_mask 0, red_mask 0, reserved 0 0 0 0
image fmt: fourcc 1095911234, BGRA, byte_order VA_LSB_FIRST, bpp 32, depth 32, blue_mask 0xff, green_mask 0xff00, red_mask 0xff0000, reserved 0 0 0 0
image fmt: fourcc 1094862674, RGBA, byte_order VA_LSB_FIRST, bpp 32, depth 32, blue_mask 0xff0000, green_mask 0xff00, red_mask 0xff, reserved 0 0 0 0
image fmt: fourcc 1111970369, ARGB, byte_order VA_LSB_FIRST, bpp 32, depth 32, blue_mask 0xff0000, green_mask 0xff00, red_mask 0xff, reserved 0 0 0 0
image fmt: fourcc 1481787202, BGRX, byte_order VA_LSB_FIRST, bpp 32, depth 24, blue_mask 0xff, green_mask 0xff00, red_mask 0xff0000, reserved 0 0 0 0
image fmt: fourcc 1480738642, RGBX, byte_order VA_LSB_FIRST, bpp 32, depth 24, blue_mask 0xff0000, green_mask 0xff00, red_mask 0xff, reserved 0 0 0 0
va operation error 0x1 operation failed on line 338
got vaapi image:
image fmt: fourcc 1481787202, BGRX, byte_order VA_LSB_FIRST, bpp 32, depth 24, blue_mask 0xff, green_mask 0xff00, red_mask 0xff0000, reserved 0 0 0 0
18/09/2023 08:36:34 Listening for VNC connections on TCP port 5900
18/09/2023 08:36:34 Listening for VNC connections on TCP6 port 5900
^C[fred@大.狸.agency ~]$
```

**Comment by isjerryxiao** [comment]
It seems that mesa returns nonsense blue_mask, green_mask and red_mask.

**Comment by isjerryxiao** [comment]
Should be fixed by [c9b056a](https://github.com/isjerryxiao/kmsvnc/commit/c9b056a3f5671eedde9e04268f9b4cbed10e2785)

**Comment by ctrlcctrlv** [comment]
sorry still broken :s  

![image](https://github.com/isjerryxiao/kmsvnc/assets/838783/f555e073-dbd3-4db7-9738-2ca0df22daf0)

**Comment by ctrlcctrlv** [comment]
```
[fred@大.狸.agency ~/.cache/yay/kmsvnc-git]$ sudo kmsvnc --debug -i
drm driver is amdgpu
Plane 40 CRTC 0 FB 0 Type primary
Plane 45 CRTC 0 FB 0 Type primary
Plane 50 CRTC 0 FB 0 Type primary
Plane 55 CRTC 0 FB 0 Type primary
Plane 60 CRTC 0 FB 0 Type primary
Plane 65 CRTC 77 FB 119 Type primary
Using plane 65 to locate framebuffers
Template framebuffer is 119: 3840x2160 fourcc:875713112 mod:0 flags:2
handles 1 0 0 0
offsets 0 0 0 0
pitches 15360 0 0 0
format XR24, modifier NONE:LINEAR
va msg: VA-API version 1.20.0
va msg: Trying to open /usr/lib/dri/radeonsi_drv_video.so
va msg: Found init function __vaDriverInit_1_20
va msg: va_openDriver() returns 0
vaapi vendor Mesa Gallium driver 23.3.0-devel for AMD Radeon RX 6900 XT (navi21, LLVM 16.0.6, DRM 3.49, 6.1.54-1-lts)
selected rt_format 131072, alpha 0
image fmt: fourcc 842094158, NV12, byte_order VA_MSB_FIRST, bpp 0, depth 0, blue_mask 0, green_mask 0, red_mask 0, alpha_mask 0, reserved 0 0 0 0
image fmt: fourcc 808530000, P010, byte_order VA_MSB_FIRST, bpp 0, depth 0, blue_mask 0, green_mask 0, red_mask 0, alpha_mask 0, reserved 0 0 0 0
image fmt: fourcc 909193296, P016, byte_order VA_MSB_FIRST, bpp 0, depth 0, blue_mask 0, green_mask 0, red_mask 0, alpha_mask 0, reserved 0 0 0 0
image fmt: fourcc 808596553, I420, byte_order VA_MSB_FIRST, bpp 0, depth 0, blue_mask 0, green_mask 0, red_mask 0, alpha_mask 0, reserved 0 0 0 0
image fmt: fourcc 842094169, YV12, byte_order VA_MSB_FIRST, bpp 0, depth 0, blue_mask 0, green_mask 0, red_mask 0, alpha_mask 0, reserved 0 0 0 0
image fmt: fourcc 1448695129, YUYV, byte_order VA_MSB_FIRST, bpp 0, depth 0, blue_mask 0, green_mask 0, red_mask 0, alpha_mask 0, reserved 0 0 0 0
image fmt: fourcc 844715353, YUY2, byte_order VA_MSB_FIRST, bpp 0, depth 0, blue_mask 0, green_mask 0, red_mask 0, alpha_mask 0, reserved 0 0 0 0
image fmt: fourcc 1498831189, UYVY, byte_order VA_MSB_FIRST, bpp 0, depth 0, blue_mask 0, green_mask 0, red_mask 0, alpha_mask 0, reserved 0 0 0 0
image fmt: fourcc 808466521, Y800, byte_order VA_MSB_FIRST, bpp 0, depth 0, blue_mask 0, green_mask 0, red_mask 0, alpha_mask 0, reserved 0 0 0 0
image fmt: fourcc 1345598516, 444P, byte_order VA_MSB_FIRST, bpp 0, depth 0, blue_mask 0, green_mask 0, red_mask 0, alpha_mask 0, reserved 0 0 0 0
image fmt: fourcc 1346520914, RGBP, byte_order VA_MSB_FIRST, bpp 0, depth 0, blue_mask 0, green_mask 0, red_mask 0, alpha_mask 0, reserved 0 0 0 0
image fmt: fourcc 1095911234, BGRA, byte_order VA_LSB_FIRST, bpp 32, depth 32, blue_mask 0xff, green_mask 0xff00, red_mask 0xff0000, alpha_mask 0xff000000, reserved 0 0 0 0
image fmt: fourcc 1094862674, RGBA, byte_order VA_LSB_FIRST, bpp 32, depth 32, blue_mask 0xff0000, green_mask 0xff00, red_mask 0xff, alpha_mask 0xff000000, reserved 0 0 0 0
image fmt: fourcc 1111970369, ARGB, byte_order VA_LSB_FIRST, bpp 32, depth 32, blue_mask 0xff0000, green_mask 0xff00, red_mask 0xff, alpha_mask 0xff000000, reserved 0 0 0 0
image fmt: fourcc 1481787202, BGRX, byte_order VA_LSB_FIRST, bpp 32, depth 24, blue_mask 0xff, green_mask 0xff00, red_mask 0xff0000, alpha_mask 0, reserved 0 0 0 0
image fmt: fourcc 1480738642, RGBX, byte_order VA_LSB_FIRST, bpp 32, depth 24, blue_mask 0xff0000, green_mask 0xff00, red_mask 0xff, alpha_mask 0, reserved 0 0 0 0
va operation error 0x1 operation failed on line 386
got vaapi image:
image fmt: fourcc 1481787202, BGRX, byte_order VA_LSB_FIRST, bpp 32, depth 24, blue_mask 0xff, green_mask 0xff00, red_mask 0xff0000, alpha_mask 0, reserved 0 0 0 0
selected image format:
image fmt: fourcc 1481787202, BGRX, byte_order VA_LSB_FIRST, bpp 32, depth 24, blue_mask 0xff000000, green_mask 0xff0000, red_mask 0xff00, alpha_mask 0, reserved 0 0 0 0
24/09/2023 07:47:46 Listening for VNC connections on TCP port 5900
24/09/2023 07:47:46 Listening for VNC connections on TCP6 port 5900
24/09/2023 07:47:53   0 other clients
24/09/2023 07:47:53 Normal socket connection
24/09/2023 07:47:53 Client Protocol Version 3.8
24/09/2023 07:47:53 Protocol version sent 3.8, using 3.8
24/09/2023 07:47:53 rfbProcessClientSecurityType: executing handler for type 1
24/09/2023 07:47:53 rfbProcessClientSecurityType: returning securityResult for client rfb version >= 3.8
24/09/2023 07:47:53 Pixel format for client ::1:
24/09/2023 07:47:53   32 bpp, depth 24, little endian
24/09/2023 07:47:53   true colour: max r 255 g 255 b 255, shift r 16 g 8 b 0
24/09/2023 07:47:53 rfbProcessClientNormalMessage: ignoring unsupported encoding type Enc(0xFFFFFEC6)
24/09/2023 07:47:53 rfbProcessClientNormalMessage: ignoring unsupported encoding type Enc(0x574D5664)
24/09/2023 07:47:53 Enabling full-color cursor updates for client ::1
24/09/2023 07:47:53 Enabling X-style cursor updates for client ::1
24/09/2023 07:47:53 rfbProcessClientNormalMessage: ignoring unsupported encoding type Enc(0x574D5666)
24/09/2023 07:47:53 Enabling NewFBSize protocol extension for client ::1
24/09/2023 07:47:53 Enabling ExtDesktopSize protocol extension for client ::1
24/09/2023 07:47:53 rfbProcessClientNormalMessage: ignoring unsupported encoding type Enc(0xFFFFFEFB)
24/09/2023 07:47:53 rfbProcessClientNormalMessage: ignoring unsupported encoding type Enc(0x574D5668)
24/09/2023 07:47:53 rfbProcessClientNormalMessage: ignoring unsupported encoding type Enc(0xFFFFFECD)
24/09/2023 07:47:53 Enabling LastRect protocol extension for client ::1
24/09/2023 07:47:53 Enabling ExtendedClipboard extension for client ::1
24/09/2023 07:47:53 rfbProcessClientNormalMessage: ignoring unsupported encoding type Enc(0xFFFFFEC7)
24/09/2023 07:47:53 rfbProcessClientNormalMessage: ignoring unsupported encoding type Enc(0xFFFFFEC8)
24/09/2023 07:47:53 rfbProcessClientNormalMessage: ignoring unsupported encoding type Enc(0xFFFFFEFE)
24/09/2023 07:47:53 rfbProcessClientNormalMessage: ignoring unsupported encoding type Enc(0x00000032)
24/09/2023 07:47:53 Using compression level 2 for client ::1
24/09/2023 07:47:53 Using image quality level 8 for client ::1
24/09/2023 07:47:53 Using JPEG subsampling 0, Q92 for client ::1
24/09/2023 07:47:53 Using tight encoding for client ::1
24/09/2023 07:47:53 Sending rfbEncodingExtDesktopSize for size (3840x2160) 
24/09/2023 07:47:53 Client requested resolution change to (1896x1034)
24/09/2023 07:47:53 Sending rfbEncodingExtDesktopSize for size (3840x2160) resize prohibited
24/09/2023 07:47:53 Client requested resolution change to (1888x999)
24/09/2023 07:47:54 Sending rfbEncodingExtDesktopSize for size (3840x2160) resize prohibited
24/09/2023 07:47:56 Client ::1 gone
24/09/2023 07:47:56 Statistics             events    Transmit/ RawEquiv ( saved)
24/09/2023 07:47:56  ServerCutText       :      1 |        16/       16 (  0.0%)
24/09/2023 07:47:56  FramebufferUpdate   :     16 |         0/        0 (  0.0%)
24/09/2023 07:47:56  LastRect            :      1 |        12/       12 (  0.0%)
24/09/2023 07:47:56  tight               :    128 |     34142/ 33181056 ( 99.9%)
24/09/2023 07:47:56  RichCursor          :      1 |       255/      255 (  0.0%)
24/09/2023 07:47:56  ExtendedDesktopSize :      3 |        96/       96 (  0.0%)
24/09/2023 07:47:56  TOTALS              :    150 |     34521/ 33181435 ( 99.9%)
24/09/2023 07:47:56 Statistics             events    Received/ RawEquiv ( saved)
24/09/2023 07:47:56  PointerEvent        :     28 |       168/      168 (  0.0%)
24/09/2023 07:47:56  SetDesktopSize      :      2 |        48/       48 (  0.0%)
24/09/2023 07:47:56  ClientCutText       :      1 |        16/       16 (  0.0%)
24/09/2023 07:47:56  FramebufferUpdate   :     20 |       200/      200 (  0.0%)
24/09/2023 07:47:56  SetEncodings        :      1 |       104/      104 (  0.0%)
24/09/2023 07:47:56  SetPixelFormat      :      1 |        20/       20 (  0.0%)
24/09/2023 07:47:56  TOTALS              :     53 |       556/      556 (  0.0%)
^C[fred@大.狸.agency ~/.cache/yay/kmsvnc-git]$
```
